config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :candidates
  resources :job_offers
  resources :companies
  resources :questions
  resources :main_questions
  resources :scores
  resources :answers
  resources :pools
  resources :profiles

  resources :quizzes, except: [:create, :new, :edit]
  resources :meetings


  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations'}
  devise_for :candidates, path: '', path_names: { registration: 'devisecreate'}


  get '/main_questions/preview/:id', to: 'main_questions#preview', as: 'main_questions_preview'


  #GET /[candidat_id]+[timestamp]+[client_id]/[quiz_id]/exam
  get   '/quizzes/:secret/:id/exam', to: 'quizzes#start_exam', as: 'start_exam'
  get   '/quizzes/:secret/:id/end_exam', to: 'quizzes#end_exam', as: 'end_exam'
  post  '/quizzes/:secret/:id/exam_question', to: 'quizzes#exam_question', as: 'exam_question'

  get   '/quizzes/:id/result_exam', to: 'quizzes#result_exam', as: 'result_exam'
  post  '/quizzes/send_result/:id', to: 'quizzes#send_result', as: 'send_result'


  get   '/quizzes/:candidate_id/new', to: 'quizzes#new', as: 'new_quiz'
  get   '/quizzes/:candidate_id/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  post  '/quizzes/:candidate_id/new', to: 'quizzes#create'


  get   '/meetings/:candidate_id/book', to: 'meetings#book', as: 'book_meeting'
  post  '/meetings/book', to: 'meetings#save_book', as: 'save_book_meeting'


  get   '/candidates/select/:key_path', to: 'candidates#select_candidate', as: 'select_candidate'
  post  '/candidates/select/:key_path', to: 'candidates#selected_candidate'


  post '/meetings/forpool', to: 'meetings#meetings_for_pool', as: 'meetings_for_pool'

  get '/meetings/room/:id', to: 'meetings#candidate_meeting_room', as: 'meeting_room'
  get '/meetings/interview/room/:id', to: 'meetings#expert_meeting_room', as: 'expert_meeting_room'

  get '/dashboard', to: 'dashboard#dashboard'



  root to: 'dashboard#dashboard'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :candidate, optional: true
  belongs_to :user, optional: true
  belongs_to :report, optional: true

  after_initialize :set_default_data_state, :if => :new_record?


  enum data_state: [:free, :booked, :confirmed, :finish, :archived]


  def set_default_data_state
    self.data_state ||= :free
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy, :candidate_meeting_room, :expert_meeting_room]
  before_action :set_candidate, only: [:book, :save_book, :meetings_for_pool]
  before_action :authenticate_user!, only: [:index, :new, :edit, :create, :destroy, :expert_meeting_room]
  before_action :authenticate_candidate!, only: [:candidate_meeting_room]
  before_action :authenticate_client!, only: [:book, :save_book, :meetings_for_pool]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all.order(:date_start)
    @new_meeting = Meeting.new

    @days = Array.new
    for i in 1..7 do
      @days << [(Time.now + i.day).strftime("%A %d %B %Y"), (Time.now + i.day).strftime("%Y-%m-%d")]
    end


    @hours = Array.new
    for h in 8..22 do
      m = 0
      while m <= 45
        @hours << [" #{h.to_s}h#{m.to_s}", "#{h.to_s}:#{m.to_s}"]
        m += 15
      end
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.report = Report.new

    @meeting.date_start = (params[:meeting][:day] + " " + params[:meeting][:hour]).to_datetime
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_url, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book
    @meetings = Meeting.where(data_state: Meeting.data_states[:free])
  end

  def save_book
    @meeting = Meeting.find(params[:meeting_id])
    @meeting.candidate_id = @candidate.id
    @meeting.data_state = :booked

    generate_token
    @meeting.room = @session_id
    @meeting.candidate_token_id = @candidate_token
    @meeting.expert_token_id = @expert_token
    @meeting.comment = params[:comment]

    CandidatesMailer.confirmed_meeting(@meeting).deliver

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :book, notice: "Echec de la réservation" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
    end
      end
  end

  def meetings_for_pool
    @pool = Pool.find(params[:pool_id])
    @meetings = Meeting.where(data_state: Meeting.data_states[:free]).order(:date_start)
  end

  def expert_meeting_room
    @api_key = ENV['OT_API_KEY']

  end

  def candidate_meeting_room
    @api_key = ENV['OT_API_KEY']
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def set_candidate
      @candidate = Candidate.find(params[:candidate_id])
    end

    def generate_token
      opentok = OpenTok::OpenTok.new ENV['OT_API_KEY'], ENV['OT_SECRET']
      session = opentok.create_session
      session = opentok.create_session :archive_mode => :always, :media_mode => :routed
      @session_id = session.session_id


      @candidate_token = session.generate_token({
                                         :expire_time => Time.now.to_i+(7 * 24 * 60 * 60), # in one week
                                         :data => 'expert'
                                     });

      @expert_token = session.generate_token({
                                          :expire_time => Time.now.to_i+(7 * 24 * 60 * 60), # in one week
                                          :data => 'candidate'
                                      });

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:candidate_id, :report_id, :user_id, :date_start, :date_start_meeting, :date_end_meeting, :room, :data_state)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper


  def self.data_state_to_s meeting
    if meeting.free?
      return "Disponible"
    elsif meeting.booked?
      return "Réservé"
    elsif meeting.confirmed?
      return "Confirmé"
    elsif meeting.archived?
      return "Archivé"
    end
    return "Terminé"
  end

end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, class: 'with-border' %>
  </div>

  <div class="form-group">
    <%= form.label :date_start %>
    <%= form.datetime_select :date_start, class: 'with-border' %>
  </div>

  <div class="form-group">
    <%= form.label :room %>
    <%= form.text_field :room, class: 'with-border' %>
  </div>

  <div class="form-group">
    <%= form.label :data_state %>
    <%= form.select :data_state, options_for_select([['Disponible', :free], ['Réservé', :booked], ['Confirmé', :confirmed]], form.object.data_state), {}, {:class => 'with-border selectpicker'} %>
  </div>

  <%= form.hidden_field :data_state %>

  <%= form.hidden_field :user_id  %>

  <br>
  <br>

  <div style="height: 50px;">
    <%= form.submit "Sauvegarder", style: "display: inline-block; float: left;" %>
    <a style="display: inline-block; float: right;" href="<%= meetings_path %>" class="button red" >Annuler</a>
  </div>



<% end %>

app/views/meetings/_form_small.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Un jour :</label>
    <%= form.select "day", options_for_select(@days, 1), {}, {:class => 'with-border selectpicker'} %>
  </div>
  <br>

  <div class="form-group">
    <label>Une heure de rendez-vous (exemple :  13:15)</label>
    <%= form.text_field "hour", {:placeholder => 'HH:mm', :class => 'with-border selectpicker'}   %>
  </div>


  <%= form.hidden_field :data_state, :value => :free %>

  <%= form.hidden_field :user_id, :value => current_user.id.to_s %>

  <br>

  <div style="height: 50px;">
    <%= form.submit "Ajouter", style: "display: inline-block; float: left;" %>
  </div>



<% end %>

app/views/meetings/_select_meeting.html.erb
<%= form_tag save_book_meeting_path, locale: true do %>

  <br>
  <table class="basic-table">
    <thead>
        <tr>
            <th>Date rendez-vous</th>
            <th>Expert</th>
            <th>Choisir</th>
        </tr>
    </thead>

    <tbody>
      <% inner_html_radio = "<span class='radio-label'></span>" %>
      <% meetings.each do |meeting| %>
        <tr>
            <td><%= meeting.date_start.strftime("%A %d %B %Y à %Hh%M") %></td>
            <td><%= meeting.user.profile.full_name %></td>
            <td>
              <div class="radio">
                <input type="radio" id="meeting_id_<%= meeting.id.to_s%>" value="<%= meeting.id.to_s %>" name="meeting_id" />
                <label for="meeting_id_<%= meeting.id.to_s%>" value="<%= meeting.id.to_s %>" name="meeting_id" ><span class='radio-label'></span></label>
              </div>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

  <br>
  <br>
  <label>Commentaire à l'expert</label>
  <br>
  <input id="comment" placeholder="Editor content goes here" type="hidden" name="comment">
  <trix-editor input="comment" style="min-height: 220px"></trix-editor>
  <br>

  <%= hidden_field_tag :candidate_id, candidate.id %>
  <%= submit_tag "Valider la réservation" %>


<% end %>

app/views/meetings/book.html.erb
<div class="row">

  <div class="col">
    <%= render '/candidates/information', candidate: @candidate %>
  </div>
</div>


<div class="row">
  <div class="col-12 padding-top-10">
  </div>
</div>



<div class="row">
  <div class="col">
    <div class="dashboard-box ">
      <div class="headline">
        <h2>Choisir le rendez-vous</h2>
      </div>
      <div class="content with-padding padding-bottom-10">

        <%=  form_tag meetings_for_pool_path, :remote => true do %>

          <div class="row">
          <div class="col-8 padding-top-10">
            <label>Compétence de l'expert</label>
              <%= select_tag :pool_id, options_for_select(Pool.where(data_state: Pool.data_states[:prod]).map {|s| [s.subject, s.id]}), {:class => 'with-border selectpicker'} %>
              <%= hidden_field_tag :candidate_id, @candidate.id %>

          </div>

          <div class="col-2 padding-top-10">
            <label>&nbsp;</label>
            <%= submit_tag "Rechercher", class: "button dark" %>
          </div>
        </div>

        <% end %>

        <div id="content_meetings">
        </div>

      </div>
    </div>
  </div>
</div>

app/views/meetings/candidate_meeting_room.html.erb
<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h2>Rendez-vous avec </h2>
      </div>

      <div class="content with-padding padding-bottom-10">

        <div id="videos">
          <div id="subscriber"></div>

          <div id="publisher"></div>
        </div>


        <script type="text/javascript">


            var apiKey = "<%= @api_key %>";
            var sessionId = "<%= @meeting.room %>";
            var token = "<%= @meeting.candidate_token_id %>";

            // Handling all of our errors here by alerting them
            function handleError(error) {
                if (error) {
                    alert(error.message);
                }
            }

            // (optional) add server code here
            initializeSession();

            function initializeSession() {
                var session = OT.initSession(apiKey, sessionId);

                // Subscribe to a newly created stream
                session.on('streamCreated', function(event) {
                    session.subscribe(event.stream, 'subscriber', {
                        insertMode: 'append',
                        width: '100%',
                        height: '100%'
                    }, handleError);
                });

                // Create a publisher
                var publisher = OT.initPublisher('publisher', {
                    insertMode: 'append',
                    width: '100%',
                    height: '100%'
                }, handleError);

                // Connect to the session
                session.connect(token, function(error) {
                    // If the connection is successful, initialize a publisher and publish to the session
                    if (error) {
                        handleError(error);
                    } else {
                        session.publish(publisher, handleError);
                    }
                });
            }

        </script>

      </div>

    </div>
  </div>
</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/expert_meeting_room.html.erb
<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h2>Rendez-vous avec le candidat <%= @meeting.candidate.profile.full_name %> </h2>
      </div>


      <div class="content with-padding padding-bottom-10">

        <div id="videos">
          <div id="subscriber"></div>

          <div id="publisher"></div>
        </div>


        <script type="text/javascript">


            var apiKey = "<%= @api_key %>";
            var sessionId = "<%= @meeting.room %>";
            var token = "<%= @meeting.expert_token_id %>";

            // Handling all of our errors here by alerting them
            function handleError(error) {
                if (error) {
                    alert(error.message);
                }
            }

            // (optional) add server code here
            initializeSession();

            function initializeSession() {
                var session = OT.initSession(apiKey, sessionId);

                // Subscribe to a newly created stream
                session.on('streamCreated', function(event) {
                    session.subscribe(event.stream, 'subscriber', {
                        insertMode: 'append',
                        width: '100%',
                        height: '100%'
                    }, handleError);
                });

                // Create a publisher
                var publisher = OT.initPublisher('publisher', {
                    insertMode: 'append',
                    width: '100%',
                    height: '100%'
                }, handleError);

                // Connect to the session
                session.connect(token, function(error) {
                    // If the connection is successful, initialize a publisher and publish to the session
                    if (error) {
                        handleError(error);
                    } else {
                        session.publish(publisher, handleError);
                    }
                });
            }

        </script>

      </div>

    </div>
  </div>
</div>


<div class="row">
  <div class="col padding-top-20">
    <div class="dashboard-box margin-top-0">
      <div class="headline">
        <h2>Commentaire du client</h2>
      </div>
      <div class="content with-padding padding-bottom-10">
        <%== @meeting.comment %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col padding-top-20">
    <div class="dashboard-box margin-top-0">
      <div class="headline">
        <h2>Rapport</h2>
      </div>
      <div class="content with-padding padding-bottom-10">
        <%= render 'reports/form', report: @meeting %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<% unless notice.nil? %>
  <div class="notification notice closeable">
    <p><%= notice %></p>
    <a class="close" href="#"></a>
  </div>
<% end %>

<div class="row">
  <div class="col">


<div class="dashboard-box">
  <div class="headline">
    <h2 style="display: inline-block;">Vos rendez-vous</h2>
    <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_meeting_path %>" class="button green" data-tippy-placement="top">Ajouter</a>
  </div>
  <div class="content with-padding padding-bottom-10">
    <table class="basic-table">
      <thead>
      <tr>
        <th>Date rendez-vous</th>
        <th>Status</th>
        <th style="width:260px;">Action</th>
      </tr>
      </thead>

      <tbody>
      <% @meetings.each do |meeting| %>
        <tr>
          <td><%= meeting.date_start.strftime("%A %d %B %Y à %Hh%M") %></td>
          <td><%= MeetingsHelper.data_state_to_s meeting %></td>
          <td>
            <a href="<%= meeting_path meeting.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
            <a href="<%= edit_meeting_path meeting %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
            <a href="<%= meeting_path meeting.id %>" data-confirm="Are you sure?" rel="nofollow" class="button red" data-method="delete" title="Supprimer" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
  </div>
</div>





<div class="row">
  <div class="col">
    <div class="dashboard-box">
      <div class="headline">
        <h2 style="display: inline-block;">Ajouter un créneau</h2>

      </div>
      <div class="content with-padding padding-bottom-10">
        <%= render 'form_small', meeting: @new_meeting %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/meetings_for_pool.js.erb
$('#content_meetings').html("<%= j render( 'select_meeting', candidate: @candidate, meetings: @meetings) %>");

app/views/meetings/new.html.erb
<div class="dashboard-box">
  <div class="headline">
    <h2>Nouveau rendez-vous</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', meeting: @meeting %>
  </div>
</div>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">


  <div class="col">

    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <% if current_client.present? %>
          <h2>Rendez-vous avec l'expert : <%= @meeting.user.profile.full_name %></h2>
        <% else %>
          <h2>Rendez-vous</h2>
        <% end %>


      </div>

      <div class="content with-padding padding-bottom-30">

        <p>
          <strong>Date de l'entretien:</strong>
          <%= @meeting.date_start %>
        </p>

        <p>
          <strong>Data state:</strong>

          <%= MeetingsHelper.data_state_to_s @meeting %>
        </p>

        <p>
          <% if current_client.present? %>
          <strong>Commentaire pour l'expert</strong>
          <% else %>
            <strong>Commentaire du client</strong>
          <% end %>
          <br>
          <div style="border: 1px solid #a0a0a0; padding: 10px;">
            <%== @meeting.comment %>
          </div>

        </p>

        <br>
        <p>
          <% if current_user.present? %>
            <a href="<%= expert_meeting_room_path @meeting.id %> " class="button dark"> Accéder au rendez-vous </a>
          <% else %>
            <a href="<%= meeting_room_path @meeting.id %> " class="button dark"> Accéder au rendez-vous </a>
          <% end %>
          <br>

        </p>

      </div>

    </div>
  </div>
</div>


<% if @meeting.candidate.present? %>
<div class="row margin-top-40">

  <div class="col">
    <%= render '/candidates/information', candidate: @meeting.candidate %>
  </div>


</div>

<% end %>