config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :candidates
  resources :job_offers
  resources :companies
  resources :questions
  resources :main_questions
  resources :scores
  resources :answers
  resources :pools
  resources :profiles

  resources :quizzes, except: [:create, :new, :edit]
  resources :meetings


  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations'}
  devise_for :candidates, path: '', path_names: { registration: 'devisecreate'}


  get '/main_questions/preview/:id', to: 'main_questions#preview', as: 'main_questions_preview'


  #GET /[candidat_id]+[timestamp]+[client_id]/[quiz_id]/exam
  get   '/quizzes/:secret/:id/exam', to: 'quizzes#start_exam', as: 'start_exam'
  get   '/quizzes/:secret/:id/end_exam', to: 'quizzes#end_exam', as: 'end_exam'
  post  '/quizzes/:secret/:id/exam_question', to: 'quizzes#exam_question', as: 'exam_question'

  get   '/quizzes/:id/result_exam', to: 'quizzes#result_exam', as: 'result_exam'
  post  '/quizzes/send_result/:id', to: 'quizzes#send_result', as: 'send_result'


  get   '/quizzes/:candidate_id/new', to: 'quizzes#new', as: 'new_quiz'
  get   '/quizzes/:candidate_id/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  post  '/quizzes/:candidate_id/new', to: 'quizzes#create'


  get   '/meetings/:candidate_id/book', to: 'meetings#book', as: 'book_meeting'
  post  '/meetings/book', to: 'meetings#save_book', as: 'save_book_meeting'


  get   '/candidates/select/:key_path', to: 'candidates#select_candidate', as: 'select_candidate'
  post  '/candidates/select/:key_path', to: 'candidates#selected_candidate'


  post '/meetings/forpool', to: 'meetings#meetings_for_pool', as: 'meetings_for_pool'

  get '/meetings/room/:id', to: 'meetings#candidate_meeting_room', as: 'meeting_room'
  get '/meetings/interview/room/:id', to: 'meetings#expert_meeting_room', as: 'expert_meeting_room'

  get '/dashboard', to: 'dashboard#dashboard'



  root to: 'dashboard#dashboard'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum data_state: [:active, :archive]
  enum experience: [:junior, :confirm, :senior]
  after_initialize :set_default_data_state, :if => :new_record?

  belongs_to :profile
  accepts_nested_attributes_for :profile

  def set_default_data_state
    self.data_state ||= :active
    self.experience ||= :junior
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy, :selected_candidate]
  before_action :create_new_candidate, only: [:create]
  before_action :set_select_candidate, only: [:create, :select_candidate]

  before_action :authenticate_client!, only: [:index, :show, :new, :edit, :create, :destroy, :select_candidate, :selected_candidate]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @quizzes = Quiz.where(candidate_id: @candidate.id)
    @meetings = Meeting.where(candidate_id: @candidate.id)
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
    @candidate.profile = Profile.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  def create
    respond_to do |format|
      if @candidate.save
        if @key_path.present?

          if @key_path == NEW_MEETING_ACTION
            format.html { redirect_to new_meeeting_path(candidate_id:  @candidate.id) }
          else
            format.html { redirect_to new_quiz_path(candidate_id:  @candidate.id) }
          end

        else
          format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
          format.json { render :show, status: :created, location: @candidate }
        end
      else
        if @key_path.present?
            format.html { render :select_candidate, key_path: @key_path }
        else
          format.html { render :new }
          format.json { render json: @candidate.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
          format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
          format.json { render :show, status: :ok, location: @candidate }
      else
          format.html { render :edit }
          format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_candidate
  end

  def selected_candidate
    set_key_path
    Rails.logger.debug "KEY = PATH #{set_key_path}"
    respond_to do |format|
      if @key_path == NEW_QUIZ_ACTION
        format.html { redirect_to new_quiz_path(candidate_id:  @candidate.id) }
      else
        format.html { redirect_to book_meeting_path(candidate_id:  @candidate.id) }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    def set_key_path
      @key_path = params[:key_path]
    end

    def set_select_candidate
      if params[:key_path].present?
        @candidates = Candidate.where(data_state: Candidate.data_states[:active])
        set_key_path
        if @candidate.nil?
          @candidate = Candidate.new
          @candidate.profile = Profile.new
        end
      end
    end

    def create_new_candidate
      @candidate = Candidate.new(candidate_params)
      generated_password = Devise.friendly_token.first(8)
      @candidate.password = generated_password
      CandidatesMailer.welcome_candidate(@candidate, generated_password).deliver
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:experience, :email, :data_state, :key_path, profile_attributes: [:first_name, :last_name, :gender, :phone])
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, url: candidates_url(key_path: @key_path), local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Expérience <i class="help-icon" data-tippy-placement="right" title="Dans la technologie lié à l'embauche"></i></label>
    <%= form.select :experience, options_for_select([['Junior (- de 3 ans)', :junior], ['Confirmé (entre 3 et 6 ans)', :confirm], ['Senior (6 ans et plus)', :senior]], form.object.experience), {}, {:class => 'with-border selectpicker'} %>
  </div>
  <br>

  <div class="form-group">
    <label>Email</label>
    <%= form.text_field :email, class: 'with-border' %>
  </div>

  <%= form.fields_for :profile do |profile_form| %>

    <div class="form-group">
      <label>Titre</label>
      <%= profile_form.select :gender, options_for_select([['Non spécifié', ''], ['M.', 'M.'], ['Mme', 'Mme']], profile_form.object.gender), {}, {:class => 'with-border selectpicker'} %>
    </div>
    <br>

    <div class="form-group">
      <label>Prénom</label>
      <%= profile_form.text_field :first_name, class: 'with-border' %>
    </div>

    <div class="form-group">
      <label>Nom</label>
      <%= profile_form.text_field :last_name, class: 'with-border' %>
    </div>

    <div class="form-group">
      <label>Mobile <i class="help-icon" data-tippy-placement="right" title="Pour les rappels des rendez-vous en ligne."></i>  </label>
      <%= profile_form.text_field :phone, class: 'with-border' %>
    </div>


  <% end %>

  <div class="form-group">
    <label>Statut</label>
    <%= form.select :data_state, options_for_select([['Actif', :active], ['Archivé', :archive]], form.object.data_state), {}, {:class => 'with-border selectpicker'} %>
  </div>
  <br>


  <div style="height: 50px;">
    <%= form.submit "Sauvegarder", style: "display: inline-block; float: left;" %>
    <a style="display: inline-block; float: right;" href="<%= candidates_path %>" class="button red" >Annuler</a>
  </div>


<% end %>

app/views/candidates/_information.html.erb
<div class="dashboard-box margin-top-0">
  <!-- Headline -->
  <div class="headline">
    <h2>Candidat : <%= candidate.profile.full_name %></h2>
  </div>

  <div class="content with-padding padding-bottom-10">


    <div class="form-control padding-bottom-20">
      <span>Email : <%= candidate.email %>  </span>
    </div>

    <div class="form-control padding-bottom-20">
      <span>Téléphone : <%= candidate.profile.phone %>  </span>
    </div>


    <div class="form-control padding-bottom-20">
      <span>Expérience  : <%= candidate.experience %>  </span>

    </div>
  </div>
</div>

app/views/candidates/edit.html.erb
<div class="dashboard-box">
  <div class="headline">
    <h2>Modifier le candidat : <%= @candidate.profile.full_name %></h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', candidate: @candidate %>
  </div>
</div>

app/views/candidates/index.html.erb
<% unless notice.nil? %>
  <div class="notification notice closeable">
    <p><%= notice %></p>
    <a class="close" href="#"></a>
  </div>
<% end %>

<div class="dashboard-box">
  <div class="headline">
    <h2 style="display: inline-block;">Candidats</h2>
    <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_candidate_path %>" class="button green" data-tippy-placement="top">Ajouter</a>
  </div>
  <div class="content with-padding padding-bottom-10">
    <table class="basic-table">
      <thead>
      <tr>
        <th>Email</th>
        <th>Nom</th>
        <th style="width:260px;">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.email %> </td>
        <td><%= candidate.profile.last_name.capitalize %></td>
        <td>
          <a href="<%= candidate_path candidate.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
          <a href="<%= edit_candidate_path candidate %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
          <a href="<%= candidate_path candidate.id %>" data-confirm="Are you sure?" rel="nofollow" class="button red" data-method="delete" title="Supprimer" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/candidates/new.html.erb
<div class="dashboard-box">
  <div class="headline">
    <h2>Nouveau Candidat</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', candidate: @candidate %>
  </div>
</div>

app/views/candidates/select_candidate.html.erb
<div class="row">
  <div class="col padding-top-10 padding-bottom-20" style="text-align: center">
    <span><h2>

      <% if @key_path == NEW_QUIZ_ACTION %>
      Un nouveau test technique
        <% else %>
            Un nouveau rendez-vous avec un expert
        <% end %>


      <br> pour qui ?</h2></span>
  </div>
</div>

<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h2>Un candidat déjà existant</h2>
      </div>

      <%= form_tag select_candidate_path(:key_path => @key_path) do %>

      <div class="content with-padding padding-bottom-10">

        <%= select_tag :id, options_for_select(@candidates.map {|c| [c.profile.first_name + " " + c.profile.last_name, c.id]}),  {:class => 'with-border selectpicker', "data-live-search" => "true" } %>

        <br>

        <div style="height: 50px;">
          <%= submit_tag "Valider", style: "display: inline-block; float: left;" %>
        </div>

      </div>
      <% end  %>

    </div>
  </div>
</div>


<div class="row">
  <div class="col padding-top-10">
  </div>

  <div class="col padding-top-50 padding-bottom-20" style="text-align: center">
    <span><h2>ou </h2></span>
  </div>

  <div class="col padding-top-10">
  </div>
</div>




<div class="row">

  <div class="col padding-top-40">
    <div class="dashboard-box margin-top-0">
        <!-- Headline -->
        <div class="headline">
            <h2>Un nouveau candidat</h2>
        </div>

        <div class="content with-padding padding-bottom-10">
          <%= render 'form', candidate: @candidate, key_path: @key_path %>
        </div>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="row">

  <div class="col">
    <%= render '/candidates/information', candidate: @candidate %>
  </div>
</div>

<div class="row">
  <div class="col padding-top-10">
  </div>

  <div class="col padding-top-30" style="text-align: center">

  </div>

  <div class="col padding-top-10">
  </div>
</div>


<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h2>Test technique </h2>
      </div>

      <div class="content with-padding padding-bottom-30">
        <% if @quizzes.count == 0 %>
          <div class="padding-bottom-10" style="text-align: center;">
            <p> Aucun test de passer.</p>
            <a href="<%= new_quiz_path(:candidate_id=> @candidate.id) %>" class="button"> Créer un test technique</a>
          </div>
        <% else  %>
          <table class="basic-table">
            <thead>
            <tr>
              <th>Score final</th>
              <th>Compétence</th>
              <th>Candidat</th>
              <th style="width:340px;">Action</th>
            </tr>
            </thead>
            <tbody>
            <% @quizzes.each do |quiz| %>
              <tr>
                <td>
                  <% if quiz.completed? %>
                    <%= quiz.score_final %> sur <%= quiz.score_max %>
                  <% else %>
                    -
                  <% end %>
                </td>
                <td><%= quiz.pool.subject %></td>
                <td><%= quiz.candidate.profile.last_name %></td>
                <td>
                  <% if quiz.pending? %>
                    <a href="<%= start_exam_path(:secret => quiz.tag_secret, :id => quiz.id) %>" class="button dark" title="Lancer le test" data-tippy-placement="top" style="margin-right:10px"> <i class="icon-feather-power"></i></a>
                  <% elsif quiz.in_progress? %>
                    <a href="" class="button gray disabled" title="En cours" data-tippy-placement="top" style="margin-right:10px"> <i class="icon-feather-activity"></i></a>
                  <% elsif quiz.completed? %>
                    <a href="<%= result_exam_path(:id => quiz.id) %>" class="button dark" title="Résultat" data-tippy-placement="top" style="margin-right:10px"> <i class="icon-feather-bar-chart-2"></i></a>
                  <% end %>
                  <a href="<%= quiz_path quiz.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
                  <a href="<%= edit_quiz_path quiz %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
                  <a href="<%= quiz_path quiz.id %>" data-confirm="Are you sure?" rel="nofollow" class="button red" data-method="delete" title="Supprimer" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col padding-top-10">
  </div>

  <div class="col padding-top-10" style="text-align: center">

  </div>

  <div class="col padding-top-10">
  </div>
</div>


<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h2>Rendez-vous avec un expert </h2>
      </div>


      <div class="content with-padding padding-bottom-10">
        <% if @meetings.count == 0 %>
          <div class="padding-bottom-10" style="text-align: center;">
            <p> Aucun entretien avec un expert. </p>
            <a href="" class="button">Prendre un rendez-vous a </a>
          </div>
        <% else  %>
          <table class="basic-table">
            <thead>
            <tr>
              <th>Date rendez-vous</th>
              <th>Status</th>
              <th style="width:260px;">Action</th>
            </tr>
            </thead>

            <tbody>
            <% @meetings.each do |meeting| %>
              <tr>
                <td><%= meeting.date_start.strftime("%A %d %B %Y à %Hh%M") %></td>
                <td><%= MeetingsHelper.data_state_to_s meeting %></td>
                <td>
                  <a href="<%= meeting_path meeting.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
                  <a href="<%= edit_meeting_path meeting %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
                  <a href="<%= meeting_path meeting.id %>"  rel="nofollow" class="button red" title="Annuler" data-tippy-placement="top"><i class="icon-feather-alert-triangle"></i></a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

        <% end %>

      </div>

    </div>
  </div>
</div>


<div class="row">
  <div class="col padding-top-30">
    <a href="<%= candidates_path %>" class="button dark" > Retour </a>

  </div>

  <div class="col padding-top-10" style="text-align: center">

  </div>

  <div class="col padding-top-10">
  </div>
</div>