config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :candidates
  resources :job_offers
  resources :companies
  resources :questions
  resources :main_questions
  resources :scores
  resources :answers
  resources :pools
  resources :profiles

  resources :quizzes, except: [:create, :new, :edit]
  resources :meetings


  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations'}
  devise_for :candidates, path: '', path_names: { registration: 'devisecreate'}


  get '/main_questions/preview/:id', to: 'main_questions#preview', as: 'main_questions_preview'


  #GET /[candidat_id]+[timestamp]+[client_id]/[quiz_id]/exam
  get   '/quizzes/:secret/:id/exam', to: 'quizzes#start_exam', as: 'start_exam'
  get   '/quizzes/:secret/:id/end_exam', to: 'quizzes#end_exam', as: 'end_exam'
  post  '/quizzes/:secret/:id/exam_question', to: 'quizzes#exam_question', as: 'exam_question'

  get   '/quizzes/:id/result_exam', to: 'quizzes#result_exam', as: 'result_exam'
  post  '/quizzes/send_result/:id', to: 'quizzes#send_result', as: 'send_result'


  get   '/quizzes/:candidate_id/new', to: 'quizzes#new', as: 'new_quiz'
  get   '/quizzes/:candidate_id/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  post  '/quizzes/:candidate_id/new', to: 'quizzes#create'


  get   '/meetings/:candidate_id/book', to: 'meetings#book', as: 'book_meeting'
  post  '/meetings/book', to: 'meetings#save_book', as: 'save_book_meeting'


  get   '/candidates/select/:key_path', to: 'candidates#select_candidate', as: 'select_candidate'
  post  '/candidates/select/:key_path', to: 'candidates#selected_candidate'


  post '/meetings/forpool', to: 'meetings#meetings_for_pool', as: 'meetings_for_pool'

  get '/meetings/room/:id', to: 'meetings#candidate_meeting_room', as: 'meeting_room'
  get '/meetings/interview/room/:id', to: 'meetings#expert_meeting_room', as: 'expert_meeting_room'

  get '/dashboard', to: 'dashboard#dashboard'



  root to: 'dashboard#dashboard'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :clients
  has_many :candidates
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share commons setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :activate)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label> Nom </label>
    <%= form.text_field :name, class: 'with-border' %>
  </div>

  <div class="checkbox">
    <%= form.check_box :activate, :id => :activate %>
    <label for="<%= :activate %>" ><span class="checkbox-icon"></span> Activé</label>
  </div>


  <div style="height: 50px;">
    <%= form.submit "Valider", style: "display: inline-block; float: left;" %>
    <a style="display: inline-block; float: right;" href="<%= companies_path %>" class="button red" >Annuler</a>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="dashboard-box">
  <div class="headline">
    <h2>Modifier l'entreprise</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/index.html.erb
<% unless notice.nil? %>
  <div class="notification notice closeable">
    <p><%= notice %></p>
    <a class="close" href="#"></a>
  </div>
<% end %>

<div class="dashboard-box">
  <div class="headline">
    <h2 style="display: inline-block;">Entreprises</h2>
    <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_company_path %>" class="button green" data-tippy-placement="top">Ajouter</a>
  </div>
  <div class="content with-padding padding-bottom-10">
    <table class="basic-table">
      <thead>
      <tr>
        <th>Nom</th>
        <th>Activé</th>
        <th style="width:260px;">Action</th>
      </tr>
      </thead>

      <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.activate? ? "Oui" : "Non" %></td>
          <td>
            <a href="<%= company_path company.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
            <a href="<%= edit_company_path company %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
            <a href="<%= company_path company.id %>" data-confirm="Are you sure?" rel="nofollow" class="button red" data-method="delete" title="Supprimer" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>
  </div>
</div>

app/views/companies/new.html.erb
<div class="dashboard-box">
  <div class="headline">
    <h2>Ajouter une entreprise</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Activate:</strong>
  <%= @company.activate %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>