config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :candidates
  resources :job_offers
  resources :companies
  resources :questions
  resources :main_questions
  resources :scores
  resources :answers
  resources :pools
  resources :profiles

  resources :quizzes, except: [:create, :new, :edit]
  resources :meetings


  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations'}
  devise_for :candidates, path: '', path_names: { registration: 'devisecreate'}


  get '/main_questions/preview/:id', to: 'main_questions#preview', as: 'main_questions_preview'


  #GET /[candidat_id]+[timestamp]+[client_id]/[quiz_id]/exam
  get   '/quizzes/:secret/:id/exam', to: 'quizzes#start_exam', as: 'start_exam'
  get   '/quizzes/:secret/:id/end_exam', to: 'quizzes#end_exam', as: 'end_exam'
  post  '/quizzes/:secret/:id/exam_question', to: 'quizzes#exam_question', as: 'exam_question'

  get   '/quizzes/:id/result_exam', to: 'quizzes#result_exam', as: 'result_exam'
  post  '/quizzes/send_result/:id', to: 'quizzes#send_result', as: 'send_result'


  get   '/quizzes/:candidate_id/new', to: 'quizzes#new', as: 'new_quiz'
  get   '/quizzes/:candidate_id/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  post  '/quizzes/:candidate_id/new', to: 'quizzes#create'


  get   '/meetings/:candidate_id/book', to: 'meetings#book', as: 'book_meeting'
  post  '/meetings/book', to: 'meetings#save_book', as: 'save_book_meeting'


  get   '/candidates/select/:key_path', to: 'candidates#select_candidate', as: 'select_candidate'
  post  '/candidates/select/:key_path', to: 'candidates#selected_candidate'


  post '/meetings/forpool', to: 'meetings#meetings_for_pool', as: 'meetings_for_pool'

  get '/meetings/room/:id', to: 'meetings#candidate_meeting_room', as: 'meeting_room'
  get '/meetings/interview/room/:id', to: 'meetings#expert_meeting_room', as: 'expert_meeting_room'

  get '/dashboard', to: 'dashboard#dashboard'



  root to: 'dashboard#dashboard'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/main_question.rb
class MainQuestionValidator < ActiveModel::Validator

  def validate(record)
    record.questions.each do |question|
      check_question(question, record)
    end
  end


  def check_question(question, record)
    error_point = 0

    arr_content = []
    question.answers.each do |answer|
      if answer.point > 0
        error_point += answer.point
      end
      arr_content << answer.content
    end

    unless record.in_progress? && record.work?
      if error_point != 100
        record.errors[:point] << "Le cumul des bonnes réponses doit être égale à 1."
      end

      if arr_content.uniq.length < 4
        record.errors[:content_answer] << "Pour chaque question il doit avoir au minimum 4 réponses différentes."
      end

      if question.content.empty?
        record.errors[:content_question_empty] << "Toute les varaintes doivent avoir... une question."
      elsif question.content.length < 20
        record.errors[:size_question] << "La question doit au moins faire 20 caractères."
      end
    end

 end
end


class MainQuestion < ApplicationRecord
  validates_with MainQuestionValidator
  after_initialize :set_default_value
  belongs_to :pool
  has_many :questions
  accepts_nested_attributes_for :questions

  enum level: [:junior, :confirm, :senior]
  enum data_state: [:work, :in_progress, :wait_validation, :ready, :prod]

  def set_default_value
    self.data_state ||= :work
    self.level ||= :junior
  end

  def level_to_s
    str = "Junior"
    if self.confirm?
      str = "Confirmé"
    elsif self.senior?
      str = "Senior"
    end
    str
  end


  def data_state_to_s
    if self.work?
      return "A faire"
    elsif self.in_progress?
      return "En cours"
    elsif self.wait_validation?
      return "Acceptance"
    elsif self.ready?
      return "Validé"
    elsif self.prod?
      return "En Production"
    end
  end


end

app/controllers/main_questions_controller.rb
class MainQuestionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_main_question, only: [:show, :edit, :update, :destroy, :preview]

  # GET /main_questions
  # GET /main_questions.json
  def index
    if current_user.admin?
      @main_questions = MainQuestion.all
    else
      @main_questions = MainQuestion.where(pool_id: current_user.pool_ids)
    end
  end

  # GET /main_questions/1
  # GET /main_questions/1.json
  def show
  end

  #GET /main_questions/preview/1
  def preview
  end

  # GET /main_questions/new
  def new
    @main_question = MainQuestion.new
    @main_question.custom = false

    3.times do
      question = Question.new
      question.user = current_user
      4.times do
        answer = Answer.new
        question.answers << answer
      end
      @main_question.questions << question
    end
  end

  # GET /main_questions/1/edit
  def edit
  end

  # POST /main_questions
  # POST /main_questions.json
  def create
    @main_question = MainQuestion.new(main_question_params)

    respond_to do |format|
      if @main_question.save
        format.html { redirect_to @main_question, notice: 'Main question was successfully created.' }
        format.json { render :show, status: :created, location: @main_question }
      else
        format.html { render :new }
        format.json { render json: @main_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_questions/1
  # PATCH/PUT /main_questions/1.json
  def update
    respond_to do |format|
      if @main_question.update(main_question_params)
        format.html { redirect_to @main_question, notice: 'Main question was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_question }
      else
        format.html { render :edit }
        format.json { render json: @main_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_questions/1
  # DELETE /main_questions/1.json
  def destroy
    @main_question.destroy
    respond_to do |format|
      format.html { redirect_to main_questions_url, notice: 'Main question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share commons setup or constraints between actions.
    def set_main_question
      @main_question = MainQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_question_params
      params.require(:main_question).permit(:level, :custom, :subject, :pool_id, :data_state, questions_attributes: [:id, :content, :user_id, :main_question_id, answers_attributes: [:id, :content, :point, :best, :question_id]])
    end
end

app/helpers/main_questions_helper.rb
module MainQuestionsHelper
end

app/views/main_questions/_form.html.erb
<%= form_with(model: main_question, local: true) do |form| %>
  <% if main_question.errors.any? %>


    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(main_question.errors.count, "error") %> prohibited this main_question from
        being saved:</h4>
      <ul>
        <% main_question.errors.each do |key, message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

    </div>

  <% end %>


  <div class="row">
    <div class="col">
      <div class="form-control">
        <label> Niveau </label>
        <%= form.select :level, options_for_select([['Junior', :junior], ['Confirmé', :confirm], ['Senior', :senior]], @main_question.level), {}, {:class => 'with-border selectpicker'} %>
        </br>
      </div>

      <div class="form-control">
        <label>Sujet abordé</label>
        <%= form.text_field :subject, class: 'with-border' %>
      </div>

      <div class="form-control">
        <label> Pool de question</label>
        <% if current_user.admin? %>
          <%= form.select :pool_id, options_for_select(Pool.all.map {|s| [s.subject, s.id]}, @main_question.pool_id), {}, {:class => 'with-border selectpicker'} %>
          </div>

          <br>
          <div class="checkbox">
            <%= form.check_box :custom, :id => :custom %>
            <label for="<%= :custom %>"><span class="checkbox-icon"></span> Personalisé</label>
          </div>

        <% else %>

          <%= form.select :pool_id, options_for_select(current_user.pools.map {|s| [s.subject, s.id]}, @main_question.pool_id), {}, {:class => 'with-border selectpicker'} %>
          </div>
          <%= form.hidden_field :custom %>
        <% end %>

        </div>
  </div>

  <div class="row">
    <div class="col">
      &nbsp;
    </div>
  </div>

  <div class="row">
    <div class="col">
      <h3> Questions</h3>
      <br>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="tabs">
        <div class="tabs-header">
          <ul>
            <li class="active">
              <a href="#tab-1" data-tab-id="1">Variante 1</a>
            </li>
            <li>
              <a href="#tab-2" data-tab-id="2">Variante 2</a>
            </li>
            <li>
              <a href="#tab-3" data-tab-id="3">Variante 3</a>
            </li>
          </ul>
          <div class="tab-hover"></div>
          <nav class="tabs-nav">
            <span class="tab-prev"><i class="icon-material-outline-keyboard-arrow-left"></i></span>
            <span class="tab-next"><i class="icon-material-outline-keyboard-arrow-right"></i></span>
          </nav>
        </div>

        <% number_question = 0 %>
        <!-- Tab Content -->
        <div class="tabs-content">
          <%= form.fields_for :questions do |question_form| %>
            <% number_question += 1 %>
            <%= question_form.hidden_field :user_id %>
            <% if number_question == 1 %>
              <div class="tab active" data-tab-id="<%= number_question %>">
            <% else %>
              <div class="tab" data-tab-id="<%= number_question %>">
            <% end %>

            <%= question_form.trix_editor :content %>

            <br>

            <% number_answer = 0 %>
            <%= question_form.fields_for :answers do |answer_form| %>
              <% number_answer += 1 %>

              <div style="background-color: #EBEBEB; border-radius: 5px; padding-right: 15px; padding-left: 15px; padding-bottom: 10px; margin-bottom: 10px;">&nbsp;
                <h3> Réponse n°<%= number_answer %></h3>
                <br>
                <div class="form-control">
                  <%= answer_form.trix_editor :content %>
                </div>
                &nbsp;
                <div class="form-control">
                  Point: <br>

                  <% inner_html_radio = "<span class='radio-label'></span>" %>

                  <div class="radio">
                    <%= answer_form.radio_button :point, 100 %>
                    <%= answer_form.label :point, raw(inner_html_radio) + "1 - Bonne réponse (choix unique)", :value => "100" %>
                  </div>
                  <br>
                  <div class="radio">
                    <%= answer_form.radio_button :point, 50 %>
                    <%= answer_form.label :point, raw(inner_html_radio) + "0,5 - Bonne réponse (choix multiple)", :value => "50" %>
                  </div>
                  <br>

                  <div class="radio">
                    <%= answer_form.radio_button :point, 0 %>
                    <%= answer_form.label :point, raw(inner_html_radio) + "0 - Mauvaise réponse", :value => "0" %>
                  </div>
                  <br>

                  <div class="radio">
                    <%= answer_form.radio_button :point, -100 %>
                    <%= answer_form.label :point, raw(inner_html_radio) + "-1 - Très mauvaise réponse", :value => "-100" %>
                  </div>

                </div>
                &nbsp;
              </div>

            <% end %>
            </div>

          <% end %>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <br>

        <%= form.submit "Sauvegarder", style: "display: inline-block; float: left;" %>

        <div style="display: inline-block; float: left; width: 300px;" class="padding-left-10">
          <% if current_user.admin? %>
            <%= form.select :data_state, options_for_select([['A Faire', :work], ['En cours', :in_progress], ['Acceptance', :wait_validation], ['Prêt', :ready], ['En Production', :prod]], @main_question.data_state), {}, {:class => 'selectpicker'} %>
          <% else %>
            <%= form.select :data_state, options_for_select([['En cours', :in_progress], ['Acceptance', :wait_validation]], @main_question.data_state), {}, {:class => 'selectpicker'} %>
          <% end %>
        </div>

        <a style="display: inline-block; float: right;" href="<%= main_questions_path %>" class="button red">Annuler</a>
      </div>
    </div>

<% end %>

app/views/main_questions/edit.html.erb
<div class="dashboard-box  margin-bottom-80">
  <div class="headline">
    <h2>Modifier la question</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', main_question: @main_question %>
  </div>
</div>

app/views/main_questions/index.html.erb
<% unless notice.nil? %>
  <div class="notification notice closeable">
    <p><%= notice %></p>
    <a class="close" href="#"></a>
  </div>
<% end %>
<div class="dashboard-box">
  <div class="headline">
    <h2 style="display: inline-block;">Questions</h2>
    <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_main_question_path %>" class="button green" data-tippy-placement="top">Ajouter</a>
  </div>
  <div class="content with-padding padding-bottom-10">
    <table class="basic-table">
      <thead>
      <tr>
        <th>Sujet</th>
        <th>Etat</th>
        <th>Level</th>
        <th>Pool</th>
        <th colspan="3">Action</th>
      </tr>
      </thead>

      <tbody>
      <% @main_questions.each do |main_question| %>
        <tr>
          <td><%= main_question.subject %></td>
          <td><%= main_question.data_state_to_s %></td>
          <td><%=  main_question.level_to_s %></td>
          <td><%= main_question.pool.subject %></td>
          <td>
            <a href="<%= main_question_path main_question.id %>" class="button dark" title="Voir" data-tippy-placement="top" style="margin-right:10px"><i class="icon-feather-eye"></i></a>
            <a href="<%= edit_main_question_path main_question %>" class="button dark" title="Modifier" data-tippy-placement="top" style="margin-right:10px"><i class="icon-line-awesome-edit"></i></a>
            <a href="<%= main_question_path main_question.id %>" data-confirm="Are you sure?" rel="nofollow" class="button red" data-method="delete" title="Supprimer" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/main_questions/new.html.erb
<div class="dashboard-box margin-bottom-80">
  <div class="headline">
    <h2>Nouvelle question</h2>
  </div>
  <div class="content with-padding padding-bottom-10">
    <%= render 'form', main_question: @main_question %>
  </div>
</div>

app/views/main_questions/preview.html.erb
<script>hljs.initHighlightingOnLoad();</script>

<div class="row">
<div class="col-xl-6 padding-top-10">
  <div class="dashboard-box margin-top-0">

    <!-- Headline -->
    <div class="headline">
      <h3><i class="icon-line-awesome-question"></i>Question</h3>
    </div>

    <div class="content padding-bottom-10 padding-top-10 padding-right-10 padding-left-10" >
        <%== @main_question.questions.first.content %>
    </div>

  </div>
</div>

  <div class="col-xl-6 padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h3 style="display: inline-block;"><i class="icon-line-awesome-check-circle-o"></i> Réponses</h3>
        <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_company_path %>" class="button green" data-tippy-placement="top">Valider</a>
      </div>

      <div class="content">
        <ul class="dashboard-box-list">


          <% @main_question.questions.first.answers.each do |answer| %>

          <li>
            <div class="boxed-list-item">
              <div class="checkbox">
                <input type="checkbox" id="<%= answer.id  %>" />
                <label for="<%= answer.id  %>" ><span class="checkbox-icon"></span><%== answer.content %></label>
              </div>

            </div>
          </li>
            <% end %>

        </ul>
      </div>

    </div>
  </div>


</div>

app/views/main_questions/show.html.erb
<script>hljs.initHighlightingOnLoad();</script>
<% unless notice.nil? %>
  <div class="notification notice closeable">
    <p><%= notice %></p>
    <a class="close" href="#"></a>
  </div>
<% end %>

<div class="row">
  <div class="col padding-top-10">
    <div class="dashboard-box margin-top-0">

      <!-- Headline -->
      <div class="headline">
        <h3><i class="icon-line-awesome-question"></i>Question</h3>
      </div>

      <div class="content padding-bottom-10 padding-top-10 padding-right-10 padding-left-10">
        <%== @main_question.questions.first.content %>
      </div>

    </div>
  </div>
</div>
<div class="row">
  <div class="col padding-top-40">
    <div class="dashboard-box margin-top-0">
      <!-- Headline -->
      <div class="headline">
        <h3 style="display: inline-block;"><i class="icon-line-awesome-check-circle-o"></i> Réponses</h3>
        <a style="display: inline-block; float: right;  margin-top: -5px;" href="<%= new_company_path %>" class="button green" data-tippy-placement="top">Valider</a>
      </div>

      <div class="content">
        <% @main_question.questions.first.answers.each do |answer| %>
          <ul class="dashboard-box-list cell-response" id="answer_<%= answer.id %>">
            <li>
              <div class="boxed-list-item">
                <div class="checkbox">
                  <input type="checkbox" id="ck_answer_<%= answer.id %>"/>
                  <label for="ck_answer_<%= answer.id %>"><span class="checkbox-icon"></span><%== answer.content %>
                  </label>
                </div>
              </div>
            </li>
          </ul>
        <% end %>
      </div>

    </div>
  </div>
</div>




<script>

    $(".cell-response").click(function () {
        let idCheck = "#ck_" + this.id;

        if ($(idCheck).is(':checked')) {
            $(idCheck).prop('checked', false);
        }
        else {
            $(idCheck).prop('checked', true);
        }
    });

</script>